version: '3.7'

services:

  neo4j:
    image: "xor-tbv-neo4j:4.4.8"
    build: .
    ports:
    - "7474:7474"
    - "7473:7473"
    - "7687:7687"
    volumes:
    - neo4jtbvdb:/data
    environment:
    - NEO4J_AUTH=neo4j/PasSW0rd
    - NEO4J_dbms_security_procedures_unrestricted=apoc.*,tbv.*

volumes:
  neo4jtbvdb:
